### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kkincade** [jasonmit/ember-intl#328]
I'm attempting to use ember-intl@2.9.3 in an ember addon. My end goal is to use this addon within an actual ember application that also uses translations. However, when I try to build my addon, I get the following error:

`Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Class.module.exports.treeForApp (C:\Workspace\SVN\Software\Websites\Web\ember-development\addons\adc-list-row\node_modules\ember-intl\index.js:74:36)
    at Class._treeFor (C:\Workspace\SVN\Software\Websites\Web\ember-development\addons\adc-list-row\node_modules\ember-cli\lib\models\addon.js:322:31)
    at Class.treeFor (C:\Workspace\SVN\Software\Websites\Web\ember-development\addons\adc-list-row\node_modules\ember-cli\lib\models\addon.js:290:19)
    at C:\Workspace\SVN\Software\Websites\Web\ember-development\addons\adc-list-row\node_modules\ember-cli\lib\models\addon.js:244:32
    at Array.map (native)
    at Class.eachAddonInvoke (C:\Workspace\SVN\Software\Websites\Web\ember-development\addons\adc-list-row\node_modules\ember-cli\lib\models\addon.js:242:22)
    at Class.treeFor (C:\Workspace\SVN\Software\Websites\Web\ember-development\addons\adc-list-row\node_modules\ember-cli\lib\models\addon.js:289:20)
    at C:\Workspace\SVN\Software\Websites\Web\ember-development\addons\adc-list-row\node_modules\ember-cli\lib\broccoli\ember-app.js:446:20
    at Array.map (native)
    at EmberAddon.EmberApp.addonTreesFor (C:\Workspace\SVN\Software\Websites\Web\ember-development\addons\adc-list-row\node_modules\ember-cli\lib\broccoli\ember-app.js:444:30)`

I've created my translations file in _<addon-name>/translations/en-us.json_ and created a _config/ember-intl.js_ file with the default settings. I'm not sure what exactly the issue is here. It seems like _this_ in treeForApp (ember-intl/index.js) is not what it should be. Any help would be appreciated.

**Comment by jasonmit** [comment]
Can you push an a reproduction of the issue to GitHub?

**Comment by kkincade** [comment]
After more research, I found that the issue is actually related to an issue with ember-cli (https://github.com/ember-cli/ember-cli/issues/3718). I am using a nested ember addon in my addon, along with ember-intl. My index.js file had an call to the `included` hook in order to get the nested addon working, and that was causing issues with ember-intl. I am forking ember-cli and using this change as a fix (https://github.com/janmisek/ember-cli/commit/420bfc4d471a662661662bd0337bfe0438b7c2dc), until this issue is resolved. 

Thanks for your quick response!

**Comment by jasonmit** [comment]
Good to know and thanks for reporting back, hopefully will help others who bump up against this!
