### ISSUE TITLE
ember-getowner-polyfill depreciated

### ISSUE THREAD

**Issue by jbpresident** [jasonmit/ember-intl#406]
- [X] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [X] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 2.10.0
- Ember CLI Version:2.10.0
- Ember Intl Version: DOWNLOADED TODAY
- Browser(s): tested in Chrome
- Node Version:6.9.2

### Steps to Reproduce

DEBUG:
ember.debug.js:5732DEBUG: Ember      : 2.10.0
ember.debug.js:5732DEBUG: Ember Data : 2.10.0
ember.debug.js:5732DEBUG: Firebase   : 3.6.3
ember.debug.js:5732DEBUG: EmberFire  : 0.0.0
ember.debug.js:5732DEBUG: jQuery     : 3.1.1
ember.debug.js:5732DEBUG: -------------------------------

ember.debug.js:5563DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:16098:19)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16208:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16128:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16208:7)
        at invoke (http://localhost:4200/assets/vendor.js:16224:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16192:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:27218:37)
        at Module.callback (http://localhost:4200/assets/vendor.js:90530:21)
        at Module.exports (http://localhost:4200/assets/vendor.js:140:32)logDeprecationStackTrace @ ember.debug.js:5563HANDLERS.(anonymous function) @ ember.debug.js:5655raiseOnDeprecation @ ember.debug.js:5575HANDLERS.(anonymous function) @ ember.debug.js:5655invoke @ ember.debug.js:5671deprecate @ ember.debug.js:5639deprecate @ ember.debug.js:16665(anonymous function) @ index.js:4Module.exports @ loader.js:131Module._reify @ loader.js:164Module.reify @ loader.js:150Module.exports @ loader.js:129Module._reify @ loader.js:164Module.reify @ loader.js:150Module.exports @ loader.js:129requireModule @ loader.js:23_extractDefaultExport @ resolver.js:368resolveOther @ resolver.js:81superWrapper @ ember.debug.js:39641resolve @ ember.debug.js:5050resolve @ ember.debug.js:2445resolve @ ember.debug.js:1904resolve @ ember.debug.js:1908factoryFor @ ember.debug.js:1455instantiate @ ember.debug.js:1520lookup @ ember.debug.js:1388lookup @ ember.debug.js:1307lookup @ ember.debug.js:31779instanceInitializer @ ember-intl.js:15(anonymous function) @ ember.debug.js:4577Vertices.each @ ember.debug.js:2630Vertices.topsort @ ember.debug.js:2597DAG.topsort @ ember.debug.js:2542_runInitializer @ ember.debug.js:4592runInstanceInitializers @ ember.debug.js:4575_bootSync @ ember.debug.js:2848didBecomeReady @ ember.debug.js:3876invoke @ ember.debug.js:339flush @ ember.debug.js:407flush @ ember.debug.js:531end @ ember.debug.js:601run @ ember.debug.js:724join @ ember.debug.js:746run.join @ ember.debug.js:21562(anonymous function) @ ember.debug.js:21625mightThrow @ jquery.js:3570process @ jquery.js:3638
7livereload.js?snipver=1:74 WebSocket connection to 'ws://localhost:49154/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSEDexports.Connector.Connector.connect @ livereload.js?snipver=1:74(anonymous function) @ livereload.js?snipver=1:55(anonymous function) @ livereload.js?snipver=1:1152

**Comment by jasonmit** [comment]
Thanks, I plan to remove ember-getowner-polyfill as a direct dep soon.

**Comment by jbpresident** [comment]
Dear Jason,

many thanks for your fast answer.
I think the ember-getowner-polyfill as a direct dep is depreciated since Ember 2.3.

And thanks for your great job !

All the best 
Joachim Bäurle

**Comment by jasonmit** [comment]
@jbpresident should be resolved in 2.16.1.  Feel free to reopen if you still see it.

Thanks for opening the issue!

**Comment by jbpresident** [comment]
Dear Jason,

many many thanks from Europe ! Solved ! And so fast !

ALL THE BEST !
Joachim Bäurle

**Comment by jbpresident** [comment]
Dear Jason,

we still have on problem with ember-intl on Safari.

If we try to load the polyfill from cdn polyfills.io <http://polyfills.io/> as described in your documentation we get the following return :

/* Disable minification (remove `.min` from URL path) for more info */

and no translation of the language.


Our settings are in environment.js are :

        // ember-intl - Polyfill - Load if needed !!
        // https://github.com/jasonmit/ember-intl
        'polyfill-io': {
          features: [
            'Intl.~locale.en-US',
            'Intl.~locale.de-DE',
            'Intl.~locale.es-ES'
          ]
        }

If we do an call directly from the browser without .min we get the following return : 
/* Polyfill service v3.15.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: safari/10.0.0
 * Features requested: Intl.~locale.de-DE,Intl.~locale.en-US,Intl.~locale.es-ES
 *  */

/* No polyfills found for current settings */
and no translation of the language.


ANY IDEA ?

best regards
Joachim Bäurle

**Comment by jasonmit** [comment]
@jbpresident could you open a separate issue.  Also, when you do that if you could throw together a quick dummy app, would speed up the debug process.

**Comment by alexlafroscia** [comment]
It sounds like the polyfills just aren't needed in Safari. If you want to force them to be loaded anyway, you can do this in the config instead:

```js
'polyfill-io': {
  features: [
    'Intl.~locale.en-US',
    'Intl.~locale.de-DE',
    'Intl.~locale.es-ES'
  ],
  flags: [
    'always'
  ]
}
```
