### ISSUE TITLE
"extend" is not a member of a factory manager.

### ISSUE THREAD

**Issue by patric-eberle** [jasonmit/ember-intl#431]
- [x] I am on the [latest](https://github.com/jasonmit/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/jasonmit/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 2.7.3
- Ember CLI Version: 2.7.0
- Ember Intl Version: 2.20.1
- Browser(s): Chrome
- Node Version: 5.6.0

### Steps to Reproduce
Were using *.json translation files with dot notation keys. I've run `ember g ember-intl-dot-notation`. When opening the Ember application I get the following error, which does not appear in 2.16.1 with the same application:

```
Uncaught Error: You attempted to access "extend" on a factory manager created by container#factoryFor. "extend" is not a member of a factory manager.
    at Object.get (http://localhost:4200/assets/vendor.js:143920:21)
    at Class.localeFactory (http://localhost:4200/assets/vendor.js:194406:29)
    at Class.localeFactory (http://localhost:4200/assets/vendor.js:195437:46)
    at Class.addTranslations (http://localhost:4200/assets/vendor.js:195405:19)
    at http://localhost:4200/assets/vendor.js:195314:15
    at Array.forEach (native)
    at Class._hydrate (http://localhost:4200/assets/vendor.js:195311:20)
    at Class.init (http://localhost:4200/assets/vendor.js:195275:12)
    at Class.superWrapper [as init] (http://localhost:4200/assets/vendor.js:35494:22)
    at new Class (http://localhost:4200/assets/vendor.js:48206:14)
```

The error points to the `Klass.extend()` method in the `localeFactory` function:

```
localeFactory: function localeFactory(localeName) {
      var owner = getOwner(this);
      var lookupName = 'ember-intl@translation:' + localeName;
      var model = owner.lookup(lookupName);

      if (model) {
        return model;
      }

      var Klass = owner.factoryFor('model:ember-intl-translation') || _emberIntlModelsTranslation['default'];
      var ModelKlass = Klass.extend();

      Object.defineProperty(ModelKlass.proto(), 'localeName', {
        writable: false,
        enumerable: true,
        value: localeName
      });

      owner.register(lookupName, ModelKlass);
      model = owner.lookup(lookupName);
      this._seen.pushObject(model);

      return model;
    },
```

**Comment by jasonmit** [comment]
2.20.2 should resolve this, thanks
